### ISSUE TITLE
NewMask missing after Mac restarts

### ISSUE THREAD

**Issue by zhouxiqiao** [newswap/newmask-extension#1]
NewMask missing after Mac restarts

重启Mac后NewMask插件消失(被Chrome直接删除了，不是被关闭)

---
Device: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
OS: MacOS 10.15.6 (19G2021)
Chrome Version: 85.0.4183.102
NewMask Version: 8.0.9

**Comment by arisac** [comment]
- 直接拽 zip 会放到 chrome private 临时目录，系统重启会清空

- 应使用目录导入，并不要删除目录，此后更新均覆盖该目录

- 使用说明中应体现

**Comment by mengguang** [comment]
firefox 版本已经正式发布，用正式版吧。
firefox浏览器下载和安装插件都无需翻墙，应该是更好的推广途径。
https://addons.mozilla.org/addon/newmask/
