### ISSUE TITLE
NewSwap activity display error

### ISSUE THREAD

**Issue by arisac** [newswap/newmask-extension#11]
DISPLAYED as `ETH`

should be issue of newswap-interface?

![image](https://user-images.githubusercontent.com/63835273/93589822-71936480-f97b-11ea-8ac8-03e685f6319a.png)

**Comment by mengguang** [comment]
数据来源是 合约的名称，我们实际上并未修改。
我在newmask的表现层先遮掩一下，以后在研究优雅的解决方案。

9988b59ea8cd400909c830dbff973f45509da24f

**Comment by arisac** [comment]
confirm solved
