### ISSUE TITLE
should HIDE **fee edit button** in approve page

### ISSUE THREAD

**Issue by arisac** [newswap/newmask-extension#14]
should hide `edit` button in `1`

1. add liquidity in newswap app, pop up approve page

<img width="348" alt="Capture d’écran, le 2020-09-23 à 22 46 05" src="https://user-images.githubusercontent.com/63835273/94097262-3322fd00-fdf4-11ea-9f7f-581a3b054b3a.png">

2. click **edit** in transaction fee, the advance fee page came up

<img width="353" alt="Capture d’écran, le 2020-09-23 à 22 46 00" src="https://user-images.githubusercontent.com/63835273/94097266-35855700-fdf4-11ea-8b6a-fb986bae1fc2.png">

**Comment by arisac** [comment]
related issue solved at: https://github.com/newswap/newmask-extension/commit/8d361d8d3d5af611e961c42a4eb0ef1f05f427f5

this should be using the same fix

**Comment by mengguang** [comment]
fix fd240c5771b00128bd502904145f07ae5128139d

**Comment by arisac** [comment]
confirm solved
