### ISSUE TITLE
AMO res: Add-on Icons & Screenshots

### ISSUE THREAD

**Issue by arisac** [newswap/newmask-extension#16]
Add-on Icons & Screenshots

https://github.com/arisac/metamask-extension/tree/newmask-op-res/AMO

**Icon**

https://raw.githubusercontent.com/arisac/metamask-extension/newmask-op-res/AMO/Add-on%20icon-128.png

**Screenshot 1**

https://raw.githubusercontent.com/arisac/metamask-extension/newmask-op-res/AMO/Screenshots-1.png

**Screenshot 2**

https://raw.githubusercontent.com/arisac/metamask-extension/newmask-op-res/AMO/Screenshots-2.png

**Comment by mengguang** [comment]
已经上传。
