### ISSUE TITLE
should hide speed up button

### ISSUE THREAD

**Issue by arisac** [newswap/newmask-extension#17]
类似 #5 

交易确认过程中

点击该交易

弹出详细信息

稍等后会有 speed up 按钮出来，此处也应该隐藏

![image](https://user-images.githubusercontent.com/63835273/94330193-2c30f180-ff90-11ea-9913-6737b00d55d9.png)

![image](https://user-images.githubusercontent.com/63835273/94330233-99dd1d80-ff90-11ea-8f87-6e539771419a.png)

**Comment by mengguang** [comment]
fix 36f17b124738ac4a9dec8b44e06873f020ea694e

**Comment by arisac** [comment]
confirm solved
