### ISSUE TITLE
Search token in Add Token

### ISSUE THREAD

**Issue by arisac** [newswap/newmask-extension#4]
### reproduce
> TestNet
- Account Home > Assets > Add Token > Search Tab
- type `a`, result tokens on Ethereum

**Solution**
1. Add default token lists to search, using newswap default token list
2. temporarily disable search tab

**Comment by mengguang** [comment]
使用patch清空eth-contract-metadata数据。
d2e6c98292926eb793a00312870ee6d9a2065d82

**Comment by arisac** [comment]
resolved
