### ISSUE TITLE
custom gas fee wrong unit

### ISSUE THREAD

**Issue by arisac** [newswap/newmask-extension#5]
> TestNet

**Describe the bug**
displayed in ETH

<img width="341" alt="Capture d’écran, le 2020-09-16 à 03 38 02" src="https://user-images.githubusercontent.com/63835273/93306577-11ab8b00-f7ce-11ea-9b50-d8099f645549.png">

**To Reproduce (REQUIRED)**
1. make transfer
2. in pending status, click `speed up`

**Comment by mengguang** [comment]
hide speedup button. It's useless on newchain at this moment. 8d361d8d3d5af611e961c42a4eb0ef1f05f427f5

**Comment by arisac** [comment]
resolved
